-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/RetainedArticles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/retained_articles (
  ra_deleted_page_namespace INT DEFAULT 0 NOT NULL,
  ra_deleted_page_title VARBINARY(255) DEFAULT '' NOT NULL,
  ra_retained_page_id INT UNSIGNED DEFAULT NULL,
  ra_retained_page_namespace INT DEFAULT 0 NOT NULL,
  ra_retained_page_title VARBINARY(255) DEFAULT '' NOT NULL,
  ra_actor_id INT UNSIGNED NOT NULL,
  ra_timestamp BINARY(14) NOT NULL,
  INDEX ra_retained_page (
    ra_retained_page_namespace, ra_retained_page_title
  ),
  PRIMARY KEY(
    ra_deleted_page_namespace, ra_deleted_page_title
  )
) /*$wgDBTableOptions*/;
